output_file = "TwemojiCOLRv0.ttf"
color_format = "glyf_colr_0"
family = "Twemoji COLRv0"

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"

[master.regular.position]
wght = 400
